services:
  - type: web
    name: sparky-events
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python projectspark/manage.py collectstatic --noinput && python projectspark/manage.py migrate
    startCommand: gunicorn projectspark.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: IS_PRODUCTION
        value: "True"
      - key: USE_CELERY
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"

  - type: pserv
    name: sparky-postgres
    plan: free
    ipAllowList: []
    env: postgresql
    dbName: sparky
    user: sparky_user
