# Generated by Django 5.0.1 on 2024-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0003_delete_workhanddetail_workhand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhand',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
