# Generated by Django 5.0.1 on 2024-02-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0004_alter_workhand_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkhandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='workhand',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workhand',
            name='password',
        ),
        migrations.RemoveField(
            model_name='workhand',
            name='username',
        ),
        migrations.AddField(
            model_name='workhand',
            name='address',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhand',
            name='contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhand',
            name='workhand_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appspark.workhandcategory'),
            preserve_default=False,
        ),
    ]
