# Generated by Django 5.0.1 on 2024-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0005_workhandcategory_remove_workhand_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhand',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
