# Generated by Django 5.0.1 on 2024-02-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0006_alter_workhand_address_alter_workhand_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhand',
            name='workhand_category',
        ),
    ]
