# Generated by Django 5.0.1 on 2024-02-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0009_eventscategory_remove_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhand',
            name='profile_pic',
        ),
    ]
