# Generated by Django 5.0.1 on 2024-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0010_remove_workhand_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhand',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
