# Generated by Django 5.0.1 on 2024-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0012_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhand',
            name='city',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhand',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workhand',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
