# Generated by Django 5.0.1 on 2024-02-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0016_companyeventhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkhandApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('by_workhand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.workhand')),
                ('to_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.company')),
            ],
        ),
    ]
