# Generated by Django 5.0.1 on 2024-02-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0017_workhandapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhandapplications',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.event'),
        ),
    ]
