# Generated by Django 5.0.1 on 2024-02-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0018_workhandapplications_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhandapplications',
            old_name='by_workhand',
            new_name='workhand',
        ),
    ]
