# Generated by Django 5.0.1 on 2024-02-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0021_workhandeventhistory_workhand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(default='assets2/img/AnonymousPic.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='profile_pic',
            field=models.ImageField(default='assets2/img/AnonymousPic.png', upload_to='media'),
        ),
    ]
