# Generated by Django 5.0.1 on 2024-02-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0022_alter_company_profile_pic_alter_workhand_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=40)),
                ('feedback', models.TextField()),
                ('date', models.DateField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.event')),
                ('workhand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.workhand')),
            ],
        ),
        migrations.AddField(
            model_name='workhandapplications',
            name='feedback_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.feedback'),
        ),
    ]
