# Generated by Django 5.0.1 on 2024-02-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0023_feedback_workhandapplications_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhandeventhistory',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='workhandeventhistory',
            name='event_category',
        ),
        migrations.RemoveField(
            model_name='workhandeventhistory',
            name='workhand_category',
        ),
        migrations.RemoveField(
            model_name='workhandeventhistory',
            name='workhand_id',
        ),
        migrations.RemoveField(
            model_name='workhandapplications',
            name='feedback_id',
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('workhand_needed', models.IntegerField()),
                ('payment_range', models.FloatField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.company')),
                ('event_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.eventscategory')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.feedback')),
                ('workhand_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.workhandcategory')),
                ('workhand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.workhand')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyEventHistory',
        ),
        migrations.DeleteModel(
            name='WorkhandEventHistory',
        ),
    ]
