# Generated by Django 5.0.1 on 2024-02-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0024_remove_workhandeventhistory_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.company'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appspark.eventhistory'),
        ),
    ]
