# Generated by Django 6.0.7 on 2026-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0025_remove_eventhistory_feedback_feedback_company_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workhandapplications',
            constraint=models.UniqueConstraint(fields=('workhand', 'event'), name='unique_application_per_event'),
        ),
    ]
