# Generated by Django 6.0.7 on 2026-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appspark', '0027_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(default='assets2/img/AnonymousPic.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='profile_pic',
            field=models.ImageField(default='assets2/img/AnonymousPic.png', upload_to=''),
        ),
    ]
